version: '3.8'
services:
    client:
        container_name: client
        build:
            dockerfile: ClientDockerfile
        tty: true               # equivalent for -t
        stdin_open: true        # equivalent for -i

    server:
        container_name: server
        build:
            dockerfile: ServerDockerfile
        depends_on:
            - db
        ports: 
            - "8080:8080"
    db:
        container_name: db
        image: postgres:16.1
        restart: always
        environment:
            POSTGRES_USER: tjv
            POSTGRES_PASSWORD: tjv
            POSTGRES_DB: tjv
        ports:
            - "5432:5432"

